name: Auth Service CI

on:
  push:
    paths:
      - 'auth/**'
      - '.github/workflows/authentication.yml'
  pull_request:
    paths:
      - 'auth/**'
      - '.github/workflows/authentication.yml'
  workflow_dispatch:

jobs:
  auth-service-ci:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          cd auth/app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Auth Docker image
        run: |
          docker build -t auth-service ./auth

      - name: Test Auth container health
        run: |
          docker run -d --name auth-test -p 6000:6000 auth-service
          sleep 5
          curl --fail http://localhost:6000/health

      - name: Cleanup containers
        run: docker rm -f auth-test || true
